CC = gcc
CFLAGS = -Wall

allocator: 
	$(CC) zsfs_super_alloc.c -o ../bin/zsfs_super_allocator $(CFLAGS)  
	$(CC) zsfs_fs_allocator.c -o ../bin/zsfs_fs_allocator $(CFLAGS)  

info: 
	$(CC) zsfs_super_info.c -o ../bin/zsfs_super_info $(CFLAGS)  
